In [1]:
import foxsisim
from foxsisim.module import Module
from foxsisim.detector import Detector
from foxsisim.source import Source
from foxsisim.plotting import scatterHist
import matplotlib.pyplot as plt
from foxsisim.plotting import plot
import numpy as np

In [2]:
module = Module(radii=[5.151,3.799],
                seglen=30.0,
                base=[0,0,0],
                focal=200,
                angles=None,
                conic=False,
                core_radius=2.856)#2.856

detector = Detector(width=3.96,#0.96 
                    height=3.96,#0.96
                    normal=[0,0,1],
                    center=[0,0,230.0],
                    reso =[128,128])
source_distance = -2187.5
offaxis_angle_arcmin = 1.0

source = Source(type='point',
                center=[ source_distance * np.sin(np.deg2rad(offaxis_angle_arcmin/60.0)) , 0.0 , source_distance ]
                )

#source = Source(type='atinf',          
#                center=[ source_distance * np.sin(np.deg2rad(offaxis_angle_arcmin/60.0)) , 0.0 , -10 ],
#                color=[0,1,1],
#                width=15,
#                height=15)
rays = source.generateRays(module.targetFront, 200)
module.passRays(rays, robust=True)
detector.catchRays(rays)

0 ray bounce number 1
[ 0.00800465  0.00728948  0.99994139]
0 ray bounce number 2
None
0 ray killed by reflect
1 ray bounce number 1
[-0.00303083 -0.01067877  0.99993839]
1 ray bounce number 2
None
1 ray killed by reflect
2 ray bounce number 1
[-0.01464406  0.02676702  0.99953443]
3 ray bounce number 1
[-0.03003219  0.02820473  0.99915092]
4 ray bounce number 1
[ 0.00892006  0.04007027  0.99915705]
5 ray bounce number 1
[-0.02923834 -0.02925206  0.99914435]
6 ray bounce number 1
[ 0.02023963 -0.03562738  0.99916017]
8 ray bounce number 1
[ 0.01075158  0.00156991  0.99994097]
8 ray bounce number 2
None
8 ray killed by reflect
9 ray bounce number 1
[-0.01065391 -0.02845132  0.9995384 ]
12 ray bounce number 1
[ 0.03038362  0.02731888  0.99916491]
15 ray bounce number 1
[-0.03054626 -0.00242351  0.99953042]
16 ray bounce number 1
[ 0.01305277  0.00723461  0.99988864]
16 ray bounce number 2
None
16 ray killed by reflect
17 ray bounce number 1
[ 0.0314851   0.02607768  0.99916397]
18 ray bou

In [3]:
from foxsisim.plotting import get3dAxes
fig2 = plt.figure(figsize=(5, 5))
axes2 = get3dAxes(fig2)
rays3=[ray for ray in rays if ray.bounces==2]
module.plot3D(axes2, rays3 ,'k')
plt.show()

TypeError: plot3D() takes at most 3 arguments (4 given)

check what is happening with the plot3D() in the foxsisim.plotting import get3dAxes module