# Ray tracing test for the Laser alignment:

July 21 de 2016

In [4]:
from foxsisim.module import Module
from foxsisim.detector import Detector
from foxsisim.source import Source
from foxsisim.plotting import scatterHist
import matplotlib.pyplot as plt
import numpy as np
import cv2

# create module/detector/source objects using defaults
module = Module(radii = [5.151,4.9,4.659,4.429,4.21,4.0,3.799],
                seglen = 30.0,
                base = [0,0,0],
                angles = None)

detector = Detector(width=8, 
                    height=8,
                    normal = [0,0,1],
                    #20.32
                    #center = [0,0,230],
                    center = [0,0,227.46],
                    reso = [1024,1024])

#source = Source()

#source = Source(type='point',          
#                center=[ 0 , 0 , -2300 ],
#                color=[1,1,1])

source = Source(width=1.,          # a 1 micron
                 height=1.,         # by 1 micron
                 type='nonpoint',       # non-point source (a square region)
                 center=[1.37,0,-2350],  # centered at [x=5,y=-8,z=20000]
                 color=[0,1,0])         # and colored light blue

# 0.0 arcmin = 0.00
# 0.5 acrmin = 0.34
# 1.0 arcmin = 0.68
# 1.5 arcmin = 1.03
# 2.0 arcmin = 1.37


#  generate 1000 rays at source
rays = source.generateRays(module.targetFront, 1000)
    
# pass rays through module
module.passRays(rays, robust=True)
    
# catch rays at detector
detector.catchRays(rays)

## plot the detector  
#fig1 = plt.figure(figsize=(8,8))
#axes1 = fig1.gca()
#axes1.set_axis_off()
#detector.plotImage(axes1)



0 ray bounce number 1
[ 0.01452518 -0.00595554  0.99987677]
0 ray bounce number 2
None
0 ray killed by reflect
1 ray bounce number 1
[ 0.00363949  0.01128866  0.99992966]
1 ray bounce number 2
[ 0.00599036  0.01725744  0.99983313]
2 ray bounce number 1
[ 0.01065124  0.00674659  0.99992051]
2 ray bounce number 2
None
2 ray killed by reflect
3 ray bounce number 1
[ -1.12253858e-02   2.67150462e-04   9.99936958e-01]
3 ray bounce number 2
None
3 ray killed by reflect
4 ray bounce number 1
[-0.00781193 -0.01259973  0.9998901 ]
4 ray bounce number 2
[-0.01218662 -0.02054534  0.99971465]
4 ray bounce number 3
None
4 ray killed by reflect
5 ray bounce number 1
[ 0.00905664 -0.00942166  0.9999146 ]
6 ray bounce number 1
[-0.03575131 -0.00523769  0.99934699]
6 ray bounce number 2
None
6 ray killed by reflect
7 ray bounce number 1
[  1.38360670e-04   1.43964940e-02   9.99896356e-01]
7 ray bounce number 2
[  6.15878243e-04   2.26504211e-02   9.99743257e-01]
8 ray bounce number 1
[-0.0106895  -0.00

In [5]:
fig = plt.figure(figsize=(7,7), dpi=100)

x = np.array([ray.des[0] for ray in rays])
y = np.array([ray.des[1] for ray in rays])

# Defining colors:
colors = []
for ray in rays:
        if ray.bounces == 1: col = 'r' # red
        elif ray.bounces == 2: col = 'g' # green
        elif ray.bounces == 3: col = 'b' # blue
        else: col = 'k' # black
        colors.append(col)

# definitions for the axes 
left, width = 0.1, 0.8
bottom, height = 0.1, 0.8
rect_scatter = [left, bottom, width, height]
axScatter = fig.add_axes(rect_scatter)

axScatter.scatter(x,y,c=colors)

plt.title('Wolter-I')
lg = plt.Circle((0.,2.55),.05,color='g') # Single bounce photons
fig.gca().add_artist(lg)
plt.text(.2,2.5,'Single bounce photons',rotation=0)

lg = plt.Circle((0.,2.25),.05,color='b') # Double bounce photons
fig.gca().add_artist(lg)
plt.text(.2,2.2,'Double bounce photons',rotation=0)
extraticks=[-2.5,-1.5,-0.5,0.5,1.5,2.5]
plt.xticks(list(plt.xticks()[0]) + extraticks)
plt.yticks(list(plt.xticks()[0]) + extraticks)
plt.grid()

plt.show()

/Users/Kamilobu/anaconda/lib/python2.7/site-packages/matplotlib/collections.py:590: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if self._edgecolors == str('face'):


In [6]:
# plot the detector  
fig1 = plt.figure(figsize=(9,9))
axes1 = fig1.gca()
axes1.set_axis_off()
detector.plotImage(axes1)

plt.show()


AttributeError: Detector instance has no attribute 'plotImage'